application: u9ozdev
#application: u9ozstaging
version: 6
runtime: python27
api_version: 1
threadsafe: yes

# Probably wont be used. Needed when
# switching to new instance
inbound_services:
- warmup

# By default GAE is using 10 minutes
default_expiration: "1d"

handlers:
- url: /cms/css
  static_dir: templates/cms/css

- url: /cms/js
  static_dir: templates/cms/js

- url: /cms/template
  static_dir: templates/cms/template

- url: /cms/image
  static_dir: templates/cms/image

- url: /tou\.html
  static_files: templates/web/tou.html
  upload: templates/web/tou\.html

- url: /official\.html
  static_files: templates/web/official.html
  upload: templates/web/official\.html

- url: /credits\.html
  static_files: templates/web/credits.html
  upload: templates/web/credits\.html

- url: /(pp|privacy)\.html
  static_files: templates/web/privacy.html
  upload: templates/web/privacy\.html

- url: /privacy\.html
  static_files: templates/web/privacy.html
  upload: templates/web/privacy\.html

- url: /apple-touch-icon-(.*)
  static_files: templates/web/apple-touch-icon-\1
  upload: templates/web/apple-touch-icon-(.*)

- url: /crossdomain\.xml
  static_files: templates/web/crossdomain\.xml
  upload: templates/web/crossdomain\.xml

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /humans\.txt
  static_files: templates/web/humans.txt
  upload: templates/web/humans\.txt

- url: /sounds
  static_dir: templates/web/sounds

- url: /css/(.*)\.ttf
  static_files: templates/web/css/\1.ttf
  upload: templates/web/css/(.*).ttf
  mime_type: application/x-font-ttf

- url: /css/(.*)\.otf
  static_files: templates/web/css/\1.otf
  upload: templates/web/css/(.*).otf
  mime_type: font/opentype

- url: /css/(.*)\.woff
  static_files: templates/web/css/\1.woff
  upload: templates/web/css/(.*).woff
  mime_type: application/x-font-woff

- url: /css
  mime_type: text/css
  static_dir: templates/web/css

- url: /js/app\.js
  static_files: templates/web/js/app.min.js
  upload: templates/web/js/app\.min\.js

- url: /js/appDetect\.js
  static_files: templates/web/js/appDetect.min.js
  upload: templates/web/js/appDetect\.min\.js

- url: /js/preview\.js
  static_files: templates/web/js/preview\.min\.js
  upload: templates/web/js/preview\.min\.js

- url: /js/previewR\.js
  static_files: templates/web/js/previewR.min.js
  upload: templates/web/js/previewR\.min\.js

- url: /js/r\.js
  static_files: templates/web/js/r.min.js
  upload: templates/web/js/r\.min\.js

- url: /js/rDetect\.js
  static_files: templates/web/js/rDetect.min.js
  upload: templates/web/js/rDetect\.min\.js

- url: /js
  static_dir: templates/web/js

- url: /img
  static_dir: templates/web/img

- url: /locale
  static_dir: templates/web/locale

- url: /m/stylesheets
  static_dir: templates/web/m/stylesheets

- url: /m/javascripts
  static_dir: templates/web/m/javascripts

- url: /m/images
  static_dir: templates/web/m/images

- url: /m/videos
  mime_type: video/mp4
  static_dir: templates/web/m/videos

- url: /m/fonts/(.*)\.ttf
  static_files: templates/web/m/fonts/\1.ttf
  upload: templates/web/m/fonts/(.*).ttf
  mime_type: application/x-font-ttf

- url: /m/fonts/(.*)\.otf
  static_files: templates/web/m/fonts/\1.otf
  upload: templates/web/m/fonts/(.*).otf
  mime_type: font/opentype

- url: /m/fonts/(.*)\.woff
  static_files: templates/web/m/fonts/\1.woff
  upload: templates/web/m/fonts/(.*).woff
  mime_type: application/x-font-woff

- url: /m/fonts
  static_dir: templates/web/m/fonts

- url: /m/templates
  static_dir: templates/web/m/templates

- url: /models/(.*)
  script: static.app
  #static_dir: templates/web/models

- url: /videos
  mime_type: video/webm
  static_dir: templates/web/videos

- url: /robots\.txt
  static_files: templates/web/robots.txt
  upload: templates/web/robots\.txt

- url: /preview/zoe/js
  static_dir: templates/web/preview/zoe/js

- url: /preview/cutout/js
  static_dir: templates/web/preview/cutout/js

- url: /preview/music/js
  static_dir: templates/web/preview/music/js

- url: /tasks/clean
  script: tasks.app
  login: admin

- url: /api/.*
  script: api.app

- url: /cms.*
  script: cms.app

- url: /m
  script: web.app
  login: required

- url: /.*
  script: web.app
  login: required

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest
- name: PIL
  version: latest

builtins:
- remote_api: on

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- changelog\.txt